from dataclasses import dataclass
from pathlib import Path

from src.config.paths import PROJECT_PATHS, ProjectPaths
from src.state.clients import list_clients
from src.state.matters import all_matter_statuses
from src.state.models import ClientProfile, MatterStatus


@dataclass(frozen=True)
class ClientMatterSummary:
    matter: MatterStatus
    relative_path: str


@dataclass(frozen=True)
class ClientMatterIndexEntry:
    client: ClientProfile
    matters: list[ClientMatterSummary]


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def _sort_key(matter: MatterStatus) -> tuple[str, str]:
    touched = matter.last_touched_at or ""
    return (touched, matter.opened)


def build_client_matter_index(paths: ProjectPaths = PROJECT_PATHS) -> list[ClientMatterIndexEntry]:
    clients = list_clients(paths)
    matters = all_matter_statuses(paths)
    entries: list[ClientMatterIndexEntry] = []
    for client in clients:
        client_matters = [matter for matter in matters if matter.client == client.client_slug]
        recent = sorted(client_matters, key=_sort_key, reverse=True)[:2]
        entries.append(
            ClientMatterIndexEntry(
                client=client,
                matters=[
                    ClientMatterSummary(
                        matter=matter,
                        relative_path=str(matter.matter_dir.relative_to(paths.project_root)),
                    )
                    for matter in recent
                ],
            )
        )
    return entries


def write_client_matter_index(entries: list[ClientMatterIndexEntry], target: Path) -> None:
    lines = [
        "# Generated by the legal harness. Do not edit by hand.",
        "",
    ]
    for entry in entries:
        lines.extend(
            [
                "[[clients]]",
                f"slug = {_toml_string(entry.client.client_slug)}",
                f"display_name = {_toml_string(entry.client.display_name)}",
                f"client_type = {_toml_string(entry.client.client_type)}",
                "",
            ]
        )
        for summary in entry.matters:
            matter = summary.matter
            lines.extend(
                [
                    "[[clients.matters]]",
                    f"path = {_toml_string(summary.relative_path)}",
                    f"name = {_toml_string(matter.matter_dir.name)}",
                    f"status = {_toml_string(matter.status)}",
                    f"matter_type = {_toml_string(matter.matter_type)}",
                    f"last_touched_at = {_toml_string(matter.last_touched_at or '')}",
                    "",
                ]
            )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines).rstrip() + "\n")


def refresh_client_matter_index(paths: ProjectPaths = PROJECT_PATHS) -> list[ClientMatterIndexEntry]:
    entries = build_client_matter_index(paths)
    write_client_matter_index(entries, paths.client_matter_index)
    return entries
